### PR TITLE
Fix currentVote bug

### PR DESCRIPTION
**Pull request by lachlanjc**
Discovered a bug earlier today that prevents the `currentVote` prop from correctly going to the main App render, because `SET_CURRENT_COMBO`, which was being run after the upvoting/downvoting actions, set `currentVote` to null. Quick fix 😀

### CODE REVIEW

**Comment by lachlanjc** [comment]
Oh looks like Travis isn’t happy. I’ll take a look

**Comment by lachlanjc** [comment]
@johnotander Is it a problem if I just remove this test? https://github.com/johnotander/random-a11y/blob/master/src/store/reducers/votes/votes-test.js#L38

I mean, skipping _should_ set `currentVote` to null, but since that code is getting called also after upvotes and downvotes, maybe it should just stay out of dealing with `currentVote`?

**Comment by johnotander** [comment]
Sorry, missed this. Yep, nuke it.

**Comment by lachlanjc** [comment]
Fabulous.

**Comment by lachlanjc** [comment]
I must say, pushing code from my iPad is so awesome. I'll wait for Travis to check things out but we should be good to go now!

**Comment by johnotander** [comment]
> pushing code from my iPad

Way rad.

**Comment by lachlanjc** [comment]
Ding! Have you seen the Working Copy app?

**Comment by johnotander** [comment]
TIL 💝

**Pull request merged**
